[window]
#opacity = 0.95
blur = false


[scrolling]
history = 10000


[font]
normal = { family = "Cica", style = "Regular" }
size = 12
builtin_box_drawing = true

[cursor]
style = { shape = "Block", blinking = "Always" }

[general]
live_config_reload = true

[terminal]
shell = { program = "/usr/bin/bash", args = [] }
